apiVersion: v1
kind: Template
metadata:
  name: learning-resources
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: learning-resources
    spec:
      envName: ${ENV_NAME}
      title: Learning resources
      API:
        versions:
          - v1
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - id: learningResources
          appId: learningResources
          title: Learning Resources
          href: "/openshift/learning-resources"
        - id: learningResources
          appId: learningResources
          title: Learning Resources
          href: "/ansible/learning-resources"
        - id: learningResources
          appId: learningResources
          title: Learning Resources
          href: "/insights/learning-resources"
        - id: learningResources
          appId: learningResources
          title: Learning Resources
          href: "/edge/learning-resources"
        - id: learningResources
          appId: learningResources
          title: Learning Resources
          href: "/iam/learning-resources"
      module:
        manifestLocation: /apps/learningResources/fed-mods.json
        modules:
          - id: learningResources
            module: ./RootApp
            routes:
              - pathname: "/openshift/learning-resources"
              - pathname: "/ansible/learning-resources"
              - pathname: "/insights/learning-resources"
              - pathname: "/edge/learning-resources"
              - pathname: "/settings/learning-resources"
              - pathname: "/iam/learning-resources"
        moduleID: learning-resources
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/learning-resources
